/* ───────────── THEME TOKENS ─────────────
   5 themes for the English Teaching Board redesign.
   Every mockup pulls colors/fonts/radii from these tokens.
   ─────────────────────────────────────── */

const THEMES = {
  editorial: {
    id: 'editorial',
    name: 'Editorial Academic',
    tagline: 'Tạp chí thời trang gặp từ điển Oxford — blush cream + wine rose, Playfair serif',
    mode: 'light',
    fonts: {
      display: '"Playfair Display", "Source Serif 4", Georgia, serif',
      body: '"Inter", system-ui, sans-serif',
      mono: '"JetBrains Mono", ui-monospace, monospace',
      phonetic: '"Playfair Display", Georgia, serif',
    },
    color: {
      bg: '#f5ece8',
      bgSoft: '#ecdcd5',
      surface: '#fdf6f3',
      surfaceAlt: '#f1e2dc',
      ink: '#1f1518',
      inkSoft: '#4a3a3d',
      muted: '#8a7378',
      mutedSoft: '#bca5aa',
      line: '#dec9c5',
      lineSoft: '#ecdcd7',
      accent: '#9d2449',
      accentHover: '#b13559',
      accentSoft: '#fae5ec',
      accent2: '#1e3a8a',
      success: '#15803d',
      warn: '#a16207',
      danger: '#b91c1c',
    },
    radius: { sm: '3px', md: '6px', lg: '10px', xl: '14px' },
    shadow: {
      sm: '0 1px 0 rgba(157,36,73,.06)',
      md: '0 2px 8px rgba(157,36,73,.08), 0 1px 0 rgba(157,36,73,.04)',
      lg: '0 12px 32px rgba(157,36,73,.14)',
    },
    chrome: { kind: 'editorial' },
  },

  linear: {
    id: 'linear',
    name: 'Linear Minimal',
    tagline: 'Notion/Linear style — neutrals + indigo, dense + clean',
    mode: 'light',
    fonts: {
      display: '"Inter", system-ui, sans-serif',
      body: '"Inter", system-ui, sans-serif',
      mono: '"JetBrains Mono", ui-monospace, monospace',
      phonetic: '"Newsreader", Georgia, serif',
    },
    color: {
      bg: '#fafafa',
      bgSoft: '#f4f4f5',
      surface: '#ffffff',
      surfaceAlt: '#f9fafb',
      ink: '#0a0a0a',
      inkSoft: '#27272a',
      muted: '#71717a',
      mutedSoft: '#a1a1aa',
      line: '#e4e4e7',
      lineSoft: '#f1f1f3',
      accent: '#4f46e5',
      accentHover: '#4338ca',
      accentSoft: '#eef2ff',
      accent2: '#0ea5e9',
      success: '#059669',
      warn: '#d97706',
      danger: '#dc2626',
    },
    radius: { sm: '4px', md: '6px', lg: '8px', xl: '12px' },
    shadow: {
      sm: '0 1px 2px rgba(0,0,0,.04)',
      md: '0 1px 3px rgba(0,0,0,.06), 0 1px 2px rgba(0,0,0,.04)',
      lg: '0 12px 32px rgba(0,0,0,.08)',
    },
    chrome: { kind: 'linear' },
  },

  warm: {
    id: 'warm',
    name: 'Warm Tutor',
    tagline: 'Sand + terracotta + forest — ấm áp, mời gọi',
    mode: 'light',
    fonts: {
      display: '"Source Serif 4", Georgia, serif',
      body: '"DM Sans", system-ui, sans-serif',
      mono: '"DM Mono", ui-monospace, monospace',
      phonetic: '"Source Serif 4", Georgia, serif',
    },
    color: {
      bg: '#f6f1ea',
      bgSoft: '#ece3d4',
      surface: '#fffbf3',
      surfaceAlt: '#f0e8d8',
      ink: '#2a1f12',
      inkSoft: '#4a3725',
      muted: '#8a7864',
      mutedSoft: '#b8a896',
      line: '#dccdb6',
      lineSoft: '#ebe0cb',
      accent: '#c2410c',
      accentHover: '#9a3412',
      accentSoft: '#fde8d4',
      accent2: '#15803d',
      success: '#15803d',
      warn: '#b45309',
      danger: '#9f1239',
    },
    radius: { sm: '6px', md: '10px', lg: '14px', xl: '20px' },
    shadow: {
      sm: '0 1px 0 rgba(74,55,37,.06)',
      md: '0 4px 14px rgba(74,55,37,.08)',
      lg: '0 16px 40px rgba(74,55,37,.14)',
    },
    chrome: { kind: 'warm' },
  },

  studio: {
    id: 'studio',
    name: 'Studio Vibrant',
    tagline: 'Near-white + electric lime + italic serif accents',
    mode: 'light',
    fonts: {
      display: '"Instrument Serif", "Source Serif 4", Georgia, serif',
      body: '"Inter", system-ui, sans-serif',
      mono: '"JetBrains Mono", ui-monospace, monospace',
      phonetic: '"Instrument Serif", Georgia, serif',
    },
    color: {
      bg: '#f7f7f5',
      bgSoft: '#ededea',
      surface: '#ffffff',
      surfaceAlt: '#f1f1ee',
      ink: '#0c0c0a',
      inkSoft: '#2a2a26',
      muted: '#6b6b66',
      mutedSoft: '#a5a59f',
      line: '#e3e3df',
      lineSoft: '#efefeb',
      accent: '#65a30d',
      accentHover: '#4d7c0f',
      accentSoft: '#ecfccb',
      accent2: '#ea580c',
      success: '#16a34a',
      warn: '#eab308',
      danger: '#dc2626',
    },
    radius: { sm: '6px', md: '12px', lg: '18px', xl: '28px' },
    shadow: {
      sm: '0 1px 2px rgba(0,0,0,.04)',
      md: '0 2px 8px rgba(0,0,0,.06)',
      lg: '0 20px 50px rgba(0,0,0,.1)',
    },
    chrome: { kind: 'studio' },
  },

  midnight: {
    id: 'midnight',
    name: 'Midnight Focus',
    tagline: 'Dark mode mặc định — slate navy + amber, cho buổi tối',
    mode: 'dark',
    fonts: {
      display: '"Source Serif 4", Georgia, serif',
      body: '"Inter", system-ui, sans-serif',
      mono: '"JetBrains Mono", ui-monospace, monospace',
      phonetic: '"Source Serif 4", Georgia, serif',
    },
    color: {
      bg: '#0b1220',
      bgSoft: '#0f172a',
      surface: '#111c33',
      surfaceAlt: '#152340',
      ink: '#f1f5f9',
      inkSoft: '#cbd5e1',
      muted: '#94a3b8',
      mutedSoft: '#64748b',
      line: '#1e2c47',
      lineSoft: '#172037',
      accent: '#f59e0b',
      accentHover: '#fbbf24',
      accentSoft: '#3a2a0c',
      accent2: '#38bdf8',
      success: '#34d399',
      warn: '#fbbf24',
      danger: '#fb7185',
    },
    radius: { sm: '4px', md: '8px', lg: '12px', xl: '16px' },
    shadow: {
      sm: '0 1px 0 rgba(0,0,0,.3)',
      md: '0 4px 14px rgba(0,0,0,.4)',
      lg: '0 16px 40px rgba(0,0,0,.5)',
    },
    chrome: { kind: 'midnight' },
  },
};

const THEME_LIST = ['editorial', 'linear', 'warm', 'studio', 'midnight'];

window.THEMES = THEMES;
window.THEME_LIST = THEME_LIST;
